branch-defaults:
  default:
    environment: Store-backend-dev-env
environment-defaults:
  Store-backend-dev-env:
    branch: null
    repository: null
global:
  application_name: store-backend-dev
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: ahmedsaad
  sc: null
  workspace_type: Application
